name: ios-openmp
on: [push, pull_request]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
jobs:
  ios-clang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: cache-openmp
      id: cache-openmp
      uses: actions/cache@v1
      with:
        path: openmp-install
        key: openmp-ios-install-20201213
    - name: checkout-openmp
      if: steps.cache-openmp.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: llvm/llvm-project
        path: llvm-project
        ref: 36a23b33aa5ef2600e53772680fc14b4e5c676f0
    - name: openmp
      if: steps.cache-openmp.outputs.cache-hit != 'true'
      run: |
        cd llvm-project/openmp
        mkdir -p build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DIOS_PLATFORM=OS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DLIBOMP_ENABLE_SHARED=OFF -DLIBOMP_OMPT_SUPPORT=OFF -DLIBOMP_USE_HWLOC=OFF ..
        cmake --build . -j 2
        cmake --build . --target install
        mkdir $GITHUB_WORKSPACE/openmp-install
        cp -r install/* $GITHUB_WORKSPACE/openmp-install

    - name: test
      run: |
        file $GITHUB_WORKSPACE/openmp-install/lib/libomp.a

    - name: build
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=../ios.toolchain.cmake -DIOS_PLATFORM=OS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DOpenMP_C_INCLUDE_DIR="$GITHUB_WORKSPACE/openmp-install/include" -DOpenMP_CXX_INCLUDE_DIR="$GITHUB_WORKSPACE/openmp-install/include" -DOpenMP_libomp_LIBRARY="$GITHUB_WORKSPACE/openmp-install/lib/libomp.a" ..
        cmake --build . -j 2
        ./hello
