name: macos-arm64-cpu
on: [push, pull_request]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
jobs:
  macos-clang:
    runs-on: macos-latest
    steps:
    - name: build
      run: cat /Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/mach/machine.h
