name: macos-arm64-openmp
on: [push, pull_request]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
jobs:
  macos-clang:
    runs-on: macos-latest
    steps:
    - name: build
      run: |
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/openmp-11.0.0.src.tar.xz
        tar -xf openmp-11.0.0.src.tar.xz
        cd openmp-11.0.0.src
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DLIBOMP_ENABLE_SHARED=OFF -DLIBOMP_OMPT_SUPPORT=OFF -DLIBOMP_USE_HWLOC=OFF ..
        cmake --build .
        find .
