name: pnnx-release
on: push

jobs:
  windows-2019:
    runs-on: windows-2019
    steps:
    - name: setup libtorch
      run: |
        Invoke-WebRequest -Uri https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.10.0%2Bcpu.zip -OutFile libtorch-win-shared-with-deps-1.10.0+cpu.zip
        7z x libtorch-win-shared-with-deps-1.10.0+cpu.zip

    - name: ncnn
      uses: actions/checkout@v2
      with:
        repository: nihui/ncnn
        path: ncnn
        ref: pnnx

    - name: build-pnnx
      run: |
        cd ncnn/tools/pnnx
        mkdir build && cd build
        cmake -DTorch_INSTALL_DIR="$env:GITHUB_WORKSPACE/libtorch" ..
        cmake --build . --config Release -j 2

  macos-1015:
    runs-on: macos-10.15
    steps:
    - name: setup libtorch
      run: |
        wget https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.10.0.zip
        unzip -q libtorch-macos-1.10.0.zip

    - name: ncnn
      uses: actions/checkout@v2
      with:
        repository: nihui/ncnn
        path: ncnn
        ref: pnnx

    - name: build-pnnx
      run: |
        cd ncnn/tools/pnnx
        mkdir build && cd build
        cmake -DTorch_INSTALL_DIR="$GITHUB_WORKSPACE/libtorch" -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . -j 2

  ubuntu-1804:
    runs-on: ubuntu-18.04
    steps:
    - name: setup libtorch
      run: |
        wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.10.0%2Bcpu.zip
        unzip -q libtorch-cxx11-abi-shared-with-deps-1.10.0+cpu.zip

    - name: ncnn
      uses: actions/checkout@v2
      with:
        repository: nihui/ncnn
        path: ncnn
        ref: pnnx

    - name: build-pnnx
      run: |
        cd ncnn/tools/pnnx
        mkdir build && cd build
        cmake -DTorch_INSTALL_DIR="$GITHUB_WORKSPACE/libtorch" -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . -j 2
