name: release
on: push

jobs:
  pnnx:
    runs-on: ubuntu-20.04
    steps:
    - name: pytorch
      run: |
        pip3 install --user torch==1.10.0+cpu torchvision==0.11.1+cpu torchaudio==0.10.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html

    - name: ncnn
      uses: actions/checkout@v2
      with:
        repository: nihui/ncnn
        path: ncnn
        ref: pnnx

    - name: build
      run: |
        cd ncnn/tools/pnnx
        mkdir build && cd build
        cmake ..
        cmake --build . -j 2
    - name: test
      run: |
        cd ncnn/tools/pnnx
        cd build && ctest --output-on-failure
