name: release
on: push

jobs:
  windows-vs2019-gpu:
    runs-on: windows-latest
    steps:
    - name: vulkansdk
      run: |
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.2.189.0/windows/VulkanSDK-1.2.189.0-Installer.exe?Human=true -OutFile VulkanSDK.exe
        $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
        $installer.WaitForExit();
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.2.189.0/windows/vulkan-runtime-components.zip?Human=true -OutFile VulkanRT.zip
        7z x -aoa ./VulkanRT.zip -oVulkanRT
    - name: cache-swiftshader
      id: cache-swiftshader
      uses: actions/cache@v2.1.6
      with:
        path: swiftshader-install
        key: swiftshader-windows-install-20211002
    - name: checkout-swiftshader
      if: steps.cache-swiftshader.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: google/swiftshader
        path: swiftshader
        ref: f43b9df4c8a9959047e2e1d7e111554ab3f9a3bf
    - name: checkout-swiftshader-submodules
      if: steps.cache-swiftshader.outputs.cache-hit != 'true'
      run: |
        cd swiftshader
        git -c submodule."third_party/git-hooks".update=none submodule update --init --recursive
    - name: swiftshader
      if: steps.cache-swiftshader.outputs.cache-hit != 'true'
      run: |
        cd swiftshader
        mkdir build-vs2019; cd build-vs2019
        cmake -DCMAKE_INSTALL_PREFIX=install -DSWIFTSHADER_BUILD_EGL=FALSE -DSWIFTSHADER_BUILD_GLESv2=FALSE -DSWIFTSHADER_BUILD_GLES_CM=FALSE -DSWIFTSHADER_BUILD_VULKAN=TRUE -DSWIFTSHADER_BUILD_PVR=FALSE -DSWIFTSHADER_BUILD_TESTS=FALSE -DSWIFTSHADER_ENABLE_ASTC=FALSE -DSWIFTSHADER_WARNINGS_AS_ERRORS=FALSE -DREACTOR_BACKEND=Subzero -DREACTOR_DEFAULT_OPT_LEVEL=Default -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release -j 2
        mkdir "$env:GITHUB_WORKSPACE/swiftshader-install"
        Copy-Item -Path "Windows\*" -Destination "$env:GITHUB_WORKSPACE\swiftshader-install"

    - name: cache-swiftshader-subzero
      id: cache-swiftshader-subzero
      uses: actions/cache@v2.1.6
      with:
        path: swiftshader-install-subzero
        key: swiftshader-windows-install-subzero-20211002
    - name: checkout-swiftshader-subzero
      if: steps.cache-swiftshader-subzero.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: google/swiftshader
        path: swiftshader
        ref: f43b9df4c8a9959047e2e1d7e111554ab3f9a3bf
    - name: checkout-swiftshader-subzero-submodules
      if: steps.cache-swiftshader-subzero.outputs.cache-hit != 'true'
      run: |
        cd swiftshader
        git -c submodule."third_party/git-hooks".update=none submodule update --init --recursive
    - name: swiftshader-subzero
      if: steps.cache-swiftshader-subzero.outputs.cache-hit != 'true'
      run: |
        cd swiftshader
        mkdir build-vs2019; cd build-vs2019
        cmake -DCMAKE_INSTALL_PREFIX=install -DSWIFTSHADER_BUILD_EGL=FALSE -DSWIFTSHADER_BUILD_GLESv2=FALSE -DSWIFTSHADER_BUILD_GLES_CM=FALSE -DSWIFTSHADER_BUILD_VULKAN=TRUE -DSWIFTSHADER_BUILD_PVR=FALSE -DSWIFTSHADER_BUILD_TESTS=FALSE -DSWIFTSHADER_ENABLE_ASTC=FALSE -DSWIFTSHADER_WARNINGS_AS_ERRORS=FALSE -DREACTOR_BACKEND=Subzero -DREACTOR_DEFAULT_OPT_LEVEL=Default -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release -j 2
        mkdir "$env:GITHUB_WORKSPACE/swiftshader-install-subzero"
        Copy-Item -Path "Windows\*" -Destination "$env:GITHUB_WORKSPACE\swiftshader-install-subzero"

    - name: test-none
      run: |
        .\VulkanRT\VulkanRT-1.2.189.0-Components\x64\vulkaninfo.exe

    - name: test
      run: |
        type swiftshader-install\vk_swiftshader_icd.json
        set VK_ICD_FILENAMES="$env:GITHUB_WORKSPACE\swiftshader-install\vk_swiftshader_icd.json"
        .\VulkanRT\VulkanRT-1.2.189.0-Components\x64\vulkaninfo.exe

    - name: test-subzero
      run: |
        type swiftshader-install-subzero\vk_swiftshader_icd.json
        set VK_ICD_FILENAMES="$env:GITHUB_WORKSPACE\swiftshader-install-subzero\vk_swiftshader_icd.json"
        .\VulkanRT\VulkanRT-1.2.189.0-Components\x64\vulkaninfo.exe
