name: woa-linux
on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  woa-linux:
    name: woa-linux
    runs-on: ubuntu-latest
    container: linaro/wine-arm64
    steps:
    - uses: actions/checkout@v4
    - name: msvc-wine
      env:
        WINEPREFIX: /tmp/wine-x64-prefix/
      run: |
        apt-get update
        apt-get install -y wine64 python3 msitools python3-simplejson python3-six ca-certificates winbind cmake ninja-build meson
        ln -s /usr/bin/wine /usr/bin/wine64
        xvfb-run winecfg &
        git clone --depth 1 https://github.com/mstorsjo/msvc-wine
        msvc-wine/vsdownload.py --accept-license --dest /msvc
        msvc-wine/install.sh /msvc
    - name: build
      env:
        WINEPREFIX: /tmp/wine-x64-prefix/
        CC: cl
        CXX: cl
      run: |
        export PATH=/msvc/bin/arm64:$PATH
        mkdir build && cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=Windows -DNCNN_BUILD_TESTS=ON ..
        cmake --build . --config Release -j 2
        wine-arm64 hello.exe
